USE SECONDARY ROLES NONE;

-- Create roles

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS LOADER_ROLE;
CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;

-- Grant roles to USER and SYSADMIN (single-user project)

GRANT ROLE LOADER_ROLE TO USER RAJSARDA1211;
GRANT ROLE TRANSFORMER_ROLE TO USER RAJSARDA1211;
GRANT ROLE ANALYST_ROLE TO USER RAJSARDA1211;

GRANT ROLE LOADER_ROLE TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;

-- Create database + schemas

USE ROLE SYSADMIN;


CREATE DATABASE IF NOT EXISTS OLIST_DB;

CREATE SCHEMA IF NOT EXISTS OLIST_DB.BRONZE_SCHEMA;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.SILVER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.GOLD_SCHEMA;


-- Create warehouses

CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ANALYSIS_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;


-- Grant Warehouse usage to respective roles

GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE ANALYSIS_WH TO ROLE ANALYST_ROLE;


-- Grant database + schema access

-- Loader role : 
GRANT USAGE ON DATABASE OLIST_DB TO ROLE LOADER_ROLE;
GRANT ALL ON SCHEMA BRONZE_SCHEMA TO ROLE LOADER_ROLE;

-- Transformer role:
GRANT USAGE ON DATABASE OLIST_DB TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA BRONZE_SCHEMA TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE_SCHEMA TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BRONZE_SCHEMA TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA SILVER_SCHEMA TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON SCHEMA GOLD_SCHEMA TO ROLE TRANSFORMER_ROLE;

-- Analyst role:
GRANT USAGE ON DATABASE OLIST_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA GOLD_SCHEMA TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD_SCHEMA TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOLD_SCHEMA TO ROLE ANALYST_ROLE;



