USE ROLE LOADER_ROLE;

USE SCHEMA OLIST_DB.BRONZE_SCHEMA;

-- Create File Format for CSV files

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

-- Create Stage

CREATE OR REPLACE STAGE OLIST_S3_STAGE
URL = 's3://olist-dataset-raj/'
CREDENTIALS = (AWS_KEY_ID = '<YOUR_AWS_ACCESS_KEY_ID>' AWS_SECRET_KEY = '<YOUR_AWS_SECRET_ACCESS_KEY>')
FILE_FORMAT = CSV_FORMAT;

LIST @OLIST_S3_STAGE;






