name: 'olist_dbt'
version: '1.0.0'

profile: 'olist_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  olist_dbt:
    silver:
      +materialized: incremental
      +on_schema_change: append_new_columns
      
      stg_geolocation:
        +materialized: table

    gold:
      +schema: GOLD_SCHEMA

      dims:
        +materialized: table

      facts:
        +materialized: incremental

      obt:
        +materialized: table
